env-name: FetchPickAndPlace-v1
n-epochs: 50
n-cycles: 50
n-batches: 40
save-interval: 5
seed: 123
num_workers: 1
replay-strategy: future
clip-return: 50
save-dir: saved_models/
noise-eps: 0.2
random-eps: 0.3
buffer-size: 1000000
replay-k: 4
clip-obs: 200
batch-size: 256
gamma: 0.98
actor-l2: 1
lr-actor: 0.001
lr-critic: 0.001
polyak: 0.95
n-test-rollouts: 10
clip-range: 5
demo-length: 20
cuda: 1
num-rollouts-per-mpi: 2
