batch_size: 256
expl_noise: 0.1
gamma: 0.99
hidden_size: 256
lr: 0.0003
noise_clip: 0.5
noise_type: action
param_noise_mean: 0
param_noise_std: 0.01
policy_freq: 2
policy_noise: 0.2
save_interval: 2000
start_steps: 10000
tau: 0.005
